USE [master]
GO

/****** Object:  Database [wordlbook]    Script Date: 21/4/2022 16:20:15 ******/
CREATE DATABASE [wordlbook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'wordlbook', FILENAME = N'E:\E\Programas\MSSQL15.SQLEXPRESS\MSSQL\DATA\wordlbook.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'wordlbook_log', FILENAME = N'E:\E\Programas\MSSQL15.SQLEXPRESS\MSSQL\DATA\wordlbook_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [wordlbook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [wordlbook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [wordlbook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [wordlbook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [wordlbook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [wordlbook] SET ARITHABORT OFF 
GO

ALTER DATABASE [wordlbook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [wordlbook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [wordlbook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [wordlbook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [wordlbook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [wordlbook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [wordlbook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [wordlbook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [wordlbook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [wordlbook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [wordlbook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [wordlbook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [wordlbook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [wordlbook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [wordlbook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [wordlbook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [wordlbook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [wordlbook] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [wordlbook] SET  MULTI_USER 
GO

ALTER DATABASE [wordlbook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [wordlbook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [wordlbook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [wordlbook] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [wordlbook] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [wordlbook] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [wordlbook] SET QUERY_STORE = OFF
GO

ALTER DATABASE [wordlbook] SET  READ_WRITE 
GO

